### ISSUE TITLE
Binary media types

### ISSUE THREAD

**Issue by joshm91** [berislavlopac/plambdapi#1]
Hey, thanks for writing this! It came days before we decided to attempt a similar thing and now have a modified version of it up and running.

We deploy directly with CloudFormation rather than Terraform so I don't know if Terraform somehow mitigates the issues I originally had with getting this up and running correctly, but I found that file downloads would only work properly once adding:

```
application/zip
application/octet-stream
*/*
```

as "Binary media types" on the API Gateway console page.

I hope this can help anyone else who stumbles across the same issue.
Thanks again!

**Comment by berislavlopac** [comment]
Hi Josh, thanks for the comment. This is a good point -- I have actually set those content types manually on my initial implementation, but have forgot to add them to the Terraform file.
