### ISSUE TITLE
Authorisation

### ISSUE THREAD

**Issue by berislavlopac** [berislavlopac/plambdapi#3]
Explore and if possible implement what is needed to be able to require authorization before using the API. Probably requires changing API Gateway configuration.

**Comment by Jawvig** [comment]
There are a couple of options we looked at and spiked for this on AWS API Gateway. One is implementing a simple API Key, the collection of which can be managed inside API Gateway. The other is using AWS IAM authentication, which requires a bit of faffing around signing requests but there is decent client API support across lots of languages. There's the ability to hook other authorizers in too, but we didn't look into that.

**Comment by berislavlopac** [comment]
The main question here is how it fits into `pip`, which supports basic HTTP authentication out of the box, even asking for credentials when they are not included in the URL. PEP 503 is very basic, so I don't think `pip` knows how to include custom headers, such as API key, when making a request.

**Comment by berislavlopac** [comment]
Closing as the project is being archived.
