### ISSUE TITLE
[api gateway's URL]

### ISSUE THREAD

**Issue by tonsquemike** [berislavlopac/plambdapi#6]
I follow the tutorial and terminal shown `Apply complete! Resources: 7 added, 0 changed, 0 destroyed`
However i can´t find the api gateway url. I tried with https://xqqbbdgaic.execute-api.eu-west-1.amazonaws.com/ but response is `{"message":"Forbidden"}`

**Comment by berislavlopac** [comment]
Closing as the project is being archived.
