### ISSUE TITLE
Unable to download package

### ISSUE THREAD

**Issue by ASangave** [berislavlopac/plambdapi#7]
I can see all terraform resources created. Also, deployed API to get url and uploaded .whl packages to S3 bucket. But nothing happens by running below command
`pip install --extra-index-url=https://fbesa5m17k.execute-api.us-east-2.amazonaws.com/test/{proxy+} aditi-itsdangerous`

It's not downloading the package.

**Comment by ASangave** [comment]
![image](https://user-images.githubusercontent.com/26111123/234857120-d944a02f-48ad-4361-bb96-1f0345e0f09f.png)
Even from UI, it's not downloading whl file

**Comment by berislavlopac** [comment]
Hi Aditi! My apologies, but this project hasn't been touched in years and is not really maintained. 😞 The recommended approach for custom package index on AWS is to use [CodeArtifact](https://aws.amazon.com/codeartifact/), which supports the free tier for small volumes.
